apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: leases.akka.io
spec:
  group: akka.io
  version: v1
  scope: Namespaced
  names:
    plural: leases
    singular: lease
    kind: Lease
    shortNames:
      - le